### ISSUE TITLE
Add more functionality to off-screen cameras

### ISSUE THREAD

**Issue by costashatz** [resibots/robot_dart#16]
Add more functionality to off-screen cameras (see #15):
  - Add possibility to attach camera to a body
  - Add possibility for camera to follow a skeleton or body
  - Visual improvements

**Comment by Aneoshun** [comment]
Additional functionalities: 
- Add a black and white mode (to generate single channel images, useful in some instances)
- Adjust projection matrix to unsure correct display ratio (a square should display as a square regardless of the selected resolution...)

**Comment by costashatz** [comment]
This should be fixed by #27 (only for the Mangum integration though)..
