### ISSUE TITLE
issue on installation magnum plugins with makefile

### ISSUE THREAD

**Issue by pngsyr** [resibots/robot_dart#198]
when i try to run this cmake -DCMAKE_BUILD_TYPE=Release -DWITH_ASSIMPIMPORTER=ON -DWITH_DDSIMPORTER=ON -DWITH_JPEGIMPORTER=ON -DWITH_OPENGEXIMPORTER=ON -DWITH_PNGIMPORTER=ON -DWITH_TINYGLTFIMPORTER=ON -DWITH_STBTRUETYPEFONT=ON .. # this will enable quite a few Magnum Plugins that are not necessarily needed for robot_dart (please refer to the documentation of Magnum for more details on selecting only the ones that you need) i get this kind of error
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)

**Comment by costashatz** [comment]
You haven't installed all the `Magnum` dependencies. Please check [here](https://github.com/resibots/robot_dart/blob/master/ci/install_packages.sh#L15) for the needed packages.

**Comment by pngsyr** [comment]
Thank you for the answer, these i have to download manually
