### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by costashatz** [resibots/robot_dart#23]
[This line](https://github.com/resibots/robot_dart/blob/master/src/robot_dart/graphics/camera_osr.hpp#L93) gives me a segmentation fault in Ubuntu 18.04 with OSG 3.2.. Looking at the OSG code, I think that we do not need this line. @Aneoshun can you check if without this line the parallel implementation works fine?

**Comment by costashatz** [comment]
@Aneoshun any news on this?

**Comment by Aneoshun** [comment]
Hi @costashatz, That's weird as it does not create a segfault on my side with the same setup (18.04, OSG 3.2). However, this line is not really required. It's just to make sure that this pointer is reset, while this is normally done automatically. I tried my code with and without this line and I see no difference.

**Comment by costashatz** [comment]
@Aneoshun Great! I am removing this line then from master.. Thanks!
