### ISSUE TITLE
Add files needed for cmake integration

### ISSUE THREAD

**Issue by jbmouret** [resibots/robot_dart#45]
We should be able to use waf to create these files.

**Comment by costashatz** [comment]
In case this is useful: [FindRobotDART.zip](https://github.com/resibots/robot_dart/files/4606690/FindRobotDART.zip)

**Comment by jbmouret** [comment]
Perfect. This will be very useful.

**Comment by jbmouret** [comment]
see #51

**Comment by costashatz** [comment]
This should be solved by #51...
