### ISSUE TITLE
RobotDARTConfig.cmake.in requires eigen3 3.3

### ISSUE THREAD

**Issue by dalinel** [resibots/robot_dart#77]
In [RobotDARTConfig.cmake.in:](https://github.com/resibots/robot_dart/blob/master/cmake/RobotDARTConfig.cmake.in) 
`find_dependency(Eigen3 3.3 REQUIRED NO_MODULE)`
Forces the user to have Eigen3 with a version > 3.3 which is not the case in the waf installation
Can it be changed to `find_dependency(Eigen3 REQUIRED NO_MODULE)` ?

**Comment by costashatz** [comment]
DART requires Eigen v3.9.2 at least (see [here](https://github.com/dartsim/dart/blob/master/cmake/DARTFindEigen3.cmake#L13)), so I think we should adapt both CMake and `waf` to require this.

**Comment by jbmouret** [comment]
You mean 3.2.92 right?

**Comment by costashatz** [comment]
> You mean 3.2.92 right?

Yes. You are right..
